apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  namespace: default
spec:
  selector:
    app: ubuntuvm
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: ubuntu
    protocol: TCP
    port: 22
    targetPort: 22