apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: wyze-bridge
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store # Must match SecretStore on the cluster

  target:
    name: wyze-bridge # Name for the secret to be created on the cluster
    creationPolicy: Owner

  data:
    - secretKey: WYZE_EMAIL # Key given to the secret to be created on the cluster
      remoteRef:
        key: /k8s/wyze-bridge/email # Full path of the secret on Akeyless
    - secretKey: WYZE_PASSWORD # Key given to the secret to be created on the cluster
      remoteRef:
        key: /k8s/wyze-bridge/password # Full path of the secret on Akeyless
