kind: Service
apiVersion: v1
metadata:
  name: wyze-bridge
spec:
  selector:
    name: wyze-bridge
  type:  LoadBalancer
  ports:
  - port: 8554
    targetPort: 8554
    name: rtsp
  - port: 8888
    targetPort: 8888
    name: http
  - port: 5000
    targetPort: 5000
    name: wyze-bridge-home
  - port: 1935
    targetPort: 1935
    name: rtmp