apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath-external-hdd
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /external-hdd/k8s
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer