defectdojo:
  django:
    ingress:
      enabled: false
      activatetlS: false
  createSecret: true
  createRedisSecret: false
  createRabbitMqSecret: true
  createPostgresqlSecret: true
  createMysqlSecret: false
  # database: mysql
  initializer:
    keepSeconds: 120
    resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256MMi
  postgresql:
    enabled: true
  mysql:
    enabled: false
  
