defectdojo:
  django:
    ingress:
      enabled: false
      activatetlS: false
  createSecret: true
  createRedisSecret: false
  createRabbitMqSecret: true
  createPostgresqlSecret: true
  createMysqlSecret: false
