apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mealie-postgres

spec:
  replicas: 3
  image: postgres:14.1

  database:
    size: 10Gi

  customConfig: mealie-postgres-conf
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubegres-password
          key: POSTGRES_PASSWORD

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubegres-password
          key: replicationPassword
    - name: POSTGRES_MY_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubegres-password
          key: POSTGRES_MY_DB_PASSWORD
