apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres

spec:
  replicas: 3
  image: postgres:14.1

  database:
    size: 10Gi

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mealie-postgres-password
          key: POSTGRES_PASSWORD

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mealie-postgres-password
          key: replicationPassword
