apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: mealie-postgresql
spec:
  teamId: mealie
  volume:
    size: 8Gi
  numberOfInstances: 2
  users:
    # database owner
    zalando:
    - superuser
    - createdb
    mealie: []

  databases:
    mealie: zalando
  postgresql:
    version: "14"