apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    name: mosquitto
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: mqtt
