apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-datadog-secret
spec:
  secretTargetRef:
    # Required: API key for your Datadog account
  - parameter: apiKey
    name: datadog-secrets
    key: datadog-api-key
    # Required: APP key for your Datadog account
  - parameter: appKey
    name: datadog-secrets
    key: datadog-app-key