apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: external-secrets
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store # Must match SecretStore on the cluster

  target:
    name: cloudflare-api-key # Name for the secret to be created on the cluster
    creationPolicy: Owner

  data:
    - secretKey: secretKey # Key given to the secret to be created on the cluster
      remoteRef:
        key: /k8s/test # Full path of the secret on Akeyless