apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio 
spec:
  selector:
    matchLabels:
      app: minio  
  template:
    metadata:
      labels:
        app: minio  
    spec:
      containers:
      - name: minio 
        image: minio/minio@sha256:eed7f8e5720272a8cb1dd5e4f97e615362ab73f2cf23b17b5470038c23fbe3d2
        args:
          - server
          - /data
          - "console-address"
          - ":9001"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        - containerPort: 9001
