apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio 
spec:
  selector:
    matchLabels:
      app: minio  
  template:
    metadata:
      labels:
        app: minio  
    spec:
      containers:
      - name: minio 
        image: minio/minio@sha256:a1a8bd4ac40ad7881a245bab97323e18f971e4d4cba2c2007ec1bedd21cbaba2
        args:
          - server
          - /data
          - "console-address"
          - ":9001"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        - containerPort: 9001
