apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio 
spec:
  selector:
    matchLabels:
      app: minio  
  template:
    metadata:
      labels:
        app: minio  
    spec:
      containers:
      - name: minio 
        image: minio/minio@sha256:1aca5f9f44595b192d3607212009dc95d4d564e7fc241f54c1f866438f934b09
        args:
          - server
          - /data
          - "console-address"
          - ":9001"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        - containerPort: 9001
