apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: openeverest
    repo: https://openeverest.github.io/helm-charts/
    version: 1.15.2
    releaseName: everest
    namespace: everest-system
    includeCRDs: true
