kube-prometheus-stack:
  prometheus:
    service:
      type: LoadBalancer
  grafana:
    service:
      type: LoadBalancer
    persistence:
      enabled: true
    additionalDataSources: 
    - name: Loki
      access: proxy
      type: loki
      url: http://loki.loki:3100
      version: 1
  