apiVersion: apps/v1
kind: Deployment
metadata:
  name:  pihole
  labels:
    name:  pihole
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  pihole
    spec:
      containers:
      - image:  pihole/pihole:2022.05
        name:  pihole
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /admin.index.php
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /admin.index.php
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: WEB_PORT
            value: '80'
          - name: VIRTUAL_HOST
            value: pi.hole
          - name: WEBPASSWORD
            valueFrom:
              secretKeyRef:
                name: pi-hole-pihole-password
                key: password
          - name: PIHOLE_DNS_
            value: 8.8.8.8;8.8.4.4      
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: dns
            containerPort: 53
            protocol: TCP
          - name: dns-udp
            containerPort: 53
            protocol: UDP
          - name: https
            containerPort: 443
            protocol: TCP
          - name: client-udp
            containerPort: 67
            protocol: UDP
      restartPolicy: Always
      imagePullPolicy: Always
      dnsConfig:
        nameservers:
          - 127.0.0.1
          - 8.8.8.8
  revisionHistoryLimit: 3