dualStack:
  enabled: true
serviceDns:
  mixedService: true
  type: LoadBalancer
  loadBalancerIP: 192.168.3.12
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
serviceDhcp:
  enabled: false
dnsmasq:
  customCnameEntries:
    - cname=services.arbitersports.com,as-phx-api-prd-staging.azurewebsites.net