dualStack:
  enabled: true
serviceDns:
  mixedService: true
  type: LoadBalancer
serviceDhcp:
  enabled: false
dnsmasq:
  customCnameEntries:
    - cname=services.arbitersports.com,as-phx-api-prd-staging.azurewebsites.net